/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncLogRouteImport } from './routes/sync-log'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as MatchupsRouteImport } from './routes/matchups'
import { Route as FreeAgentsRouteImport } from './routes/free-agents'
import { Route as IndexRouteImport } from './routes/index'

const SyncLogRoute = SyncLogRouteImport.update({
  id: '/sync-log',
  path: '/sync-log',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupsRoute = MatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAgentsRoute = FreeAgentsRouteImport.update({
  id: '/free-agents',
  path: '/free-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-agents': typeof FreeAgentsRoute
  '/matchups': typeof MatchupsRoute
  '/standings': typeof StandingsRoute
  '/sync-log': typeof SyncLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-agents': typeof FreeAgentsRoute
  '/matchups': typeof MatchupsRoute
  '/standings': typeof StandingsRoute
  '/sync-log': typeof SyncLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-agents': typeof FreeAgentsRoute
  '/matchups': typeof MatchupsRoute
  '/standings': typeof StandingsRoute
  '/sync-log': typeof SyncLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free-agents' | '/matchups' | '/standings' | '/sync-log'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free-agents' | '/matchups' | '/standings' | '/sync-log'
  id:
    | '__root__'
    | '/'
    | '/free-agents'
    | '/matchups'
    | '/standings'
    | '/sync-log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeAgentsRoute: typeof FreeAgentsRoute
  MatchupsRoute: typeof MatchupsRoute
  StandingsRoute: typeof StandingsRoute
  SyncLogRoute: typeof SyncLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync-log': {
      id: '/sync-log'
      path: '/sync-log'
      fullPath: '/sync-log'
      preLoaderRoute: typeof SyncLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchups': {
      id: '/matchups'
      path: '/matchups'
      fullPath: '/matchups'
      preLoaderRoute: typeof MatchupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-agents': {
      id: '/free-agents'
      path: '/free-agents'
      fullPath: '/free-agents'
      preLoaderRoute: typeof FreeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeAgentsRoute: FreeAgentsRoute,
  MatchupsRoute: MatchupsRoute,
  StandingsRoute: StandingsRoute,
  SyncLogRoute: SyncLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
